/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


*/

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author johnny
 */
public class formProtocolo extends javax.swing.JFrame {

    /**
     * Creates new form formProtocolo
     */
    
    /*armazena o protocolo*/
    
    List<Protocolo>listaprotocolo;
    int numero, j, i, x;
    int n = 2;
    String a, d, e;
    String tipo;
    
    
    
    public formProtocolo() {
        initComponents();
        
        numero = 0;
        listaprotocolo = new ArrayList<Protocolo>();
        
        
       
    }
    Protocolo lista = new Protocolo(); 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        caixa4 = new javax.swing.JButton();
        caixa2 = new javax.swing.JButton();
        caixa1 = new javax.swing.JButton();
        caixa3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        prioritario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rapido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        protocoloGerado = new javax.swing.JTextField();
        chamadaProtocolo = new javax.swing.JTextField();
        campoCaixa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para Caixas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        caixa4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        caixa4.setText("Caixa 4");
        caixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa4ActionPerformed(evt);
            }
        });

        caixa2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        caixa2.setText("Caixa 2");
        caixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa2ActionPerformed(evt);
            }
        });

        caixa1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        caixa1.setText("Caixa 1");
        caixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa1ActionPerformed(evt);
            }
        });

        caixa3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        caixa3.setText("Caixa 3");
        caixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixa2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(caixa3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixa4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixa2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixa4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixa3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Escolha seu tipo de atendimento");

        prioritario.setText("PrioritÃ¡rio");
        prioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioritarioActionPerformed(evt);
            }
        });

        jButton2.setText("Comum");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        rapido.setText("RÃ¡pido");
        rapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Sua senha Ã©:");

        protocoloGerado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        protocoloGerado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        protocoloGerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protocoloGeradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rapido, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(prioritario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(protocoloGerado, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prioritario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rapido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(protocoloGerado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        chamadaProtocolo.setBackground(new java.awt.Color(213, 216, 219));
        chamadaProtocolo.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        chamadaProtocolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chamadaProtocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamadaProtocoloActionPerformed(evt);
            }
        });

        campoCaixa.setBackground(new java.awt.Color(210, 215, 220));
        campoCaixa.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        campoCaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chamadaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(358, 358, 358))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(chamadaProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void protocoloGeradoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void chamadaProtocoloActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void caixa1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        /*Caixa 1*/
        
        Iterator<Protocolo> itr = listaprotocolo.iterator();
        
         while(itr.hasNext()){
            Protocolo ptr = itr.next();
            if(ptr.getTipo() == "P"){
                a = ptr.getTipo(); 
            itr.remove();
            chamadaProtocolo.setText(String.valueOf(ptr.getNumero()) + "-" + String.valueOf(ptr.getTipo()));
            campoCaixa.setText(String.valueOf("Caixa 1"));
            break;
            }
            a = null; 
        }
        
        if(a == null){
                Iterator<Protocolo> itr2 = listaprotocolo.iterator();
                while(itr2.hasNext()){
                    
                    Protocolo ptr2 = itr2.next();
                   
                    chamadaProtocolo.setText(String.valueOf(ptr2.getNumero()) + "-" + String.valueOf(ptr2.getTipo()));
                    campoCaixa.setText(String.valueOf("Caixa 1"));
                    itr2.remove();
                    break;
                }
              
             }
        
       /* while(itr.hasNext()){
            
            Protocolo ptr = itr.next();
            if(ptr.getTipo() == "P"){
            itr.remove();
            
            chamadaProtocolo.setText(String.valueOf(ptr.getNumero()) + "-" + String.valueOf(ptr.getTipo()));
            campoCaixa.setText(String.valueOf("Caixa 1"));
            
            break; 
            }
            
        }*/
       
        
    }                                      

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // cliente comum
        numero ++;
        //String tipo, int numero, String caixa
        Protocolo protocolo = new Protocolo("C", numero, "Comum"); 
        listaprotocolo.add(protocolo);
        protocoloGerado.setText(String.valueOf(protocolo.getNumero()) + "-" + String.valueOf(protocolo.getTipo()));
        
    }                                        

    private void rapidoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        //cliente Rapido
        numero ++;
        //String tipo, int numero, String caixa
        Protocolo protocolo = new Protocolo("R", numero, "Rapido"); 
        listaprotocolo.add(protocolo);
        protocoloGerado.setText(String.valueOf(protocolo.getNumero()) + "-" + String.valueOf(protocolo.getTipo()));
        
        
    }                                      

    private void prioritarioActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // Prioritario
        numero ++;
        //String tipo, int numero, String caixa
        Protocolo protocolo = new Protocolo("P", numero, "Prioritario"); 
        listaprotocolo.add(protocolo);
        protocoloGerado.setText(String.valueOf(protocolo.getNumero()) + "-" + String.valueOf(protocolo.getTipo()));
        
    }                                           

    private void campoCaixaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        
    }                                          

    private void caixa2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        Iterator<Protocolo> itr = listaprotocolo.iterator();
        
        while(itr.hasNext()){
            Protocolo ptr = itr.next();
            if(ptr.getTipo() == "R"){
                a = ptr.getTipo(); 
            itr.remove();
            chamadaProtocolo.setText(String.valueOf(ptr.getNumero()) + "-" + String.valueOf(ptr.getTipo()));
            campoCaixa.setText(String.valueOf("Caixa 2"));
            break;
            }
            a = null; 
        }
        
        if(a == null){
                Iterator<Protocolo> itr2 = listaprotocolo.iterator();
                while(itr2.hasNext()){
                    
                    Protocolo ptr2 = itr2.next();
                   
                    chamadaProtocolo.setText(String.valueOf(ptr2.getNumero()) + "-" + String.valueOf(ptr2.getTipo()));
                    campoCaixa.setText(String.valueOf("Caixa 2"));
                    itr2.remove();
                    break;
                }
              
             }
        
    }                                      

    private void caixa3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        

   
       Iterator<Protocolo> itr = listaprotocolo.iterator();
      
       
       
        while(itr.hasNext()){
          
             Protocolo ptr = itr.next(); 
              if(ptr.getTipo().equals("R")){
                a = ptr.getTipo(); 
                
                chamadaProtocolo.setText(String.valueOf(ptr.getNumero()) + "-" + String.valueOf(ptr.getTipo()));
                campoCaixa.setText(String.valueOf("Caixa 3"));
                itr.remove();              
                break;
              
            }  
            a = null;  
        }
     
     if(a == null){
                Iterator<Protocolo> itr2 = listaprotocolo.iterator();
                while(itr2.hasNext()){
                    
                    Protocolo ptr2 = itr2.next();
                   
                    chamadaProtocolo.setText(String.valueOf(ptr2.getNumero()) + "-" + String.valueOf(ptr2.getTipo()));
                    campoCaixa.setText(String.valueOf("Caixa 3"));
                    itr2.remove();
                    break;
                }
              
             }
        
    }                                      

    private void caixa4ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        
        Iterator<Protocolo> itr = listaprotocolo.iterator();
         while(itr.hasNext()){
          
             Protocolo ptr = itr.next(); 
              if(ptr.getTipo().equals("C")){
                a = ptr.getTipo(); 
                
                chamadaProtocolo.setText(String.valueOf(ptr.getNumero()) + "-" + String.valueOf(ptr.getTipo()));
                campoCaixa.setText(String.valueOf("Caixa 4"));
                itr.remove();              
                break;
              
            }  
            a = null;  
        }
     
     if(a == null){
                Iterator<Protocolo> itr2 = listaprotocolo.iterator();
                while(itr2.hasNext()){
                    
                    Protocolo ptr2 = itr2.next();
                   
                    chamadaProtocolo.setText(String.valueOf(ptr2.getNumero()) + "-" + String.valueOf(ptr2.getTipo()));
                    campoCaixa.setText(String.valueOf("Caixa 4"));
                    itr2.remove();
                    break;
                }
              
             }
       
        
       /* while(itr.hasNext()){
            
            Protocolo ptr = itr.next();
            
            if(ptr.getTipo() == "C"){
                itr.remove();
                chamadaProtocolo.setText(String.valueOf(ptr.getNumero()) + "-" + String.valueOf(ptr.getTipo()));
                campoCaixa.setText(String.valueOf("Caixa 4"));
                break;
            }
        }*/
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formProtocolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formProtocolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton caixa1;
    private javax.swing.JButton caixa2;
    private javax.swing.JButton caixa3;
    private javax.swing.JButton caixa4;
    private javax.swing.JTextField campoCaixa;
    private javax.swing.JTextField chamadaProtocolo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton prioritario;
    private javax.swing.JTextField protocoloGerado;
    private javax.swing.JButton rapido;
    // End of variables declaration                   
}


